JSON ACI encoder
aeternity/aeternity pull request #3361
Opened 2020-09-24 16:07 UTC by gorbak25

This pull request improves Sophia smart contract handling in the node.
While compiling a contract we generate in parallel an JSON ACI and store it in an ETS table.
All calls to the compiler for encoding call data were replaced by https://github.com/aeternity/aesophia_aci_encoder
This library will be used in Hyperchains in order to efficiently interact with the staking contracts and possibly other contracts(generalized accounts defined by parent chain connectors). Decoding call data will be added soon to the ACI library.

2020-09-24 19:38 UTC, hanssv requested changes

2020-09-24 19:38 UTC, hanssv commented on rebar.lock
> + {<<"aesophia">>,
Let's not put a random commit from the `master/iris` branch of `aesophia` in the aeternity node...

2020-09-25 11:37 UTC, radrow approved these changes

2020-09-25 11:37 UTC, radrow commented on apps/aechannel/test/aesc_txs_SUITE.erl
> +        %%Vsn when Vsn < ?FORTUNA_PROTOCOL_VSN; Type == hash ->
Do we need this commented line?

2020-09-25 11:37 UTC, radrow commented on apps/aecontract/test/aect_test_utils.erl
> +slow_encode_call_data(Vsn, Code, Fun, Args) ->
I love your explicitness

2020-09-25 13:35 UTC, gorbak25 commented on apps/aechannel/test/aesc_txs_SUITE.erl
> +        %%Vsn when Vsn < ?FORTUNA_PROTOCOL_VSN; Type == hash ->
I left it here for clarity

2020-09-25 14:12 UTC, hanssv reviewed
I'm missing the option to turn this off... ~If~When you want to develop the compiler/FATE further it would be useful to be able to run the tests without having to rely on a third component (that might not yet be updated). Would that make sense?

Also out of curiosity, what is the speedup compared to the (cached) call data creation? It should be really significant compared to calling the CLI compiler :-)

2020-09-25 14:48 UTC, gorbak25 commented
> I'm missing the option to turn this off... 
Will add it in a moment.

~If~When you want to develop the compiler/FATE further it would be useful to be able to run the tests without having to rely on a third component (that might not yet be updated). Would that make sense?
Good point, especially the ACI library misses some features right now(Bits type, etc..).
 
> Also out of curiosity, what is the speedup compared to the (cached) call data creation? It should be really significant compared to calling the CLI compiler :-)
Well, the main speedup comes from the ets cache, looking at the CI runs of ct-lima the aci compiler only improves the situation marginally by at most 1-2 minutes which was expected. 
The main reason for writing this library is not to speed up tests slightly but to have a flexible method for calling contracts in production, without this component any Hyperchain related contract would require a hardcoded encoder/decoder which would need to be kept in sync with the contract source code. The HC staking contract will be modified pretty often and also we have plans for parent chain connector defined smart contracts which also will be changed a lot in development - I know that we could just hardcode all encodings/decodings but this would lack the flexibility we need.

2020-09-25 15:03 UTC, hanssv commented
By (only) using this library we do loose a bit of testing of the compiler though... But calldata is fairly stable so no big issue I think.

2020-09-26 07:23 UTC, radrow commented on apps/aecontract/test/aect_test_utils.erl
> +            ct:log("ACI cache MISS :)"),
There should be a sad face imo :(

2020-09-28 06:18 UTC, hanssv approved these changes
LGTM

2020-09-28 10:10 UTC, radrow approved these changes

2020-09-28 11:43 UTC, merged