docs: Fix broken link in docs.aeternity.io
aeternity/aeternity pull request #3369
Opened 2020-10-11 17:34 UTC by saintmalik

## Summary

Easy navigation and easy reading for others.

2020-10-13 11:09 UTC, gorbak25 approved these changes

2020-10-14 15:04 UTC, hanssv commented
What is the purpose of fixing one link in the middle (or, well at the end) of one doc-file? Shouldn't we fix all of them?

2020-10-14 15:14 UTC, hanssv commented on docs/docker.md
> +For more information see [miner configuration documentation](https://docs.aeternity.io/en/stable/configuration/#miner-configuration).
```suggestion
For more information see [miner configuration documentation](configuration.md#miner-configuration).
```

2020-10-14 15:15 UTC, hanssv requested changes
It shouldn't point to https://docs.aeternity.io

2020-10-14 18:38 UTC, hanssv approved these changes

2020-10-15 13:52 UTC, gorbak25 approved these changes

2020-10-15 14:41 UTC, merged