Why?
aeternity/aeternity pull request #3391
Opened 2020-10-30 20:29 UTC by gorbak25

#3377 got really big and I'm not even close finishing this :(
I've started to separate some parts into more manageable PR's which can be merged independently of #3377.

Fixes execution time of some SC tests.
@uwiger is there a good reason for this sleep? Should we leave it in production and just remove it in tests?

2020-10-31 07:42 UTC, uwiger commented
> @uwiger is there a good reason for this sleep? Should we leave it in production and just remove it in tests?

I imagine it's left behind from some debugging spree.

2020-10-31 07:42 UTC, uwiger approved these changes

2020-11-02 17:16 UTC, radrow commented
![grafik](https://user-images.githubusercontent.com/35342116/97897924-76e41d00-1d37-11eb-8d6e-b3f3885de55e.png)

2020-11-02 17:17 UTC, radrow requested changes

2020-11-02 17:17 UTC, radrow commented on apps/aehttp/src/sc_ws_handler.erl
> +    %%timer:sleep(1000),
```suggestion
```
We got the allusion from that comment

2020-11-02 17:28 UTC, radrow approved these changes

2020-11-02 17:40 UTC, erlmachinedev commented
The timer:sleep(1000) isn't a solution and hides the real async issue. The best way is to remove sleep and to provide a fix of the bug that listed on the screenshot. 

I propose to open an appropriate issue to avoid loss of that discussion.

2020-11-02 17:42 UTC, gorbak25 commented
@erlmachinedev I think that random failures of plain.sc_ws_min_depth_is_modifiable might be fixed by #3389

2020-11-02 17:44 UTC, erlmachinedev approved these changes

2020-11-02 18:00 UTC, merged