Gb 3355 parallel tx eval 2
aeternity/aeternity pull request #3415
Opened 2020-11-26 13:18 UTC by uwiger

See issue #3355. This PR attempts to (eventually) speed up block evaluation by processing heavy transactions in parallel.

Currently, the implementation has been tested with spend txs, either accessing shared resources (same account) or being independent. The `aehttp_contract_SUITE` also double-checks with parallel eval (via dry-run over HTTP), but using only singleton lists of contract call transactions.

A preliminary performance test indicates that for now, the overhead of parallel eval is roughly 10x that of sequential eval. This should be possible to reduce, e.g. by removing the `lager:debug()` calls, but it is clear that e.g. parallel eval of `spend` txs will never pay off, since these basically only update the state trees. The expectation is that especially complex contract evaluations will benefit from parallel evaluation.

The tracing improvements rely on the uwiger/trace_runner#3 PR. The commit hash will change once that PR is merged.

2020-12-09 15:27 UTC, gorbak25 commented on apps/aecore/src/aec_trees.erl
> +              , ns      = Ns
```suggestion
              , ns        = Ns
```

2020-12-09 17:57 UTC, gorbak25 requested changes
1. Doesn't fully work - #3424 shows an failing test case
2. When restarting a worker due to dependencies we redo the (probably) already done signature check - By running the tests with {dont_verify_signature, true} the overhead between parallel and sequential TX processing becomes more reasonable
3. I don't see the option of passing the Eval CTX from the outside - If parallel tx eval got enabled by default then we will build the deps before entering aec_conductor.
4. I think we might enable this by default in case we implement #3419 - the preprocesing will be done while other blocks are being inserted - minimizing the hot path :)

2020-12-09 17:58 UTC, gorbak25 commented on apps/aecore/test/aec_trees_tests.erl
> +    SeqRes = ?TEST_MODULE:apply_txs_on_state_trees(SignedTxs, TreesIn, Env, Opts),
I would rather use timer:tc :)

2020-12-09 18:06 UTC, gorbak25 commented on apps/aecore/src/aec_trees_proxy.erl
> +                {true, Events0 ++ NewEvents};
This is linear in the first list - this might become an issue when many events were emitted

2020-12-10 16:01 UTC, uwiger commented on apps/aecore/src/aec_trees.erl
> +        #{tx_count := TxC, max_dep_count := DepC} when (DepC / TxC) > ParMaxDeps ->
Yes, this was a a deliberate trick to short-circuit that check. Should have added a comment about it, of course. :)

2021-11-17 08:59 UTC, velzevur commented
Left open so we can extract the block witness in case we consider it useful.

2025-02-12 10:54 UTC, closed without merging