Remove TTL from aega_meta_tx
aeternity/aeternity pull request #3416
Opened 2020-11-26 16:42 UTC by velzevur

Closes #3056

The work on this PR is supported by the Aeternity Crypto Foundation.

2020-11-26 19:35 UTC, hanssv requested changes

2020-11-26 19:35 UTC, hanssv commented on apps/aega/src/aega_meta_tx.erl
> -                     ttl         = maps:get(ttl, Args, 0),
This will not work? We are not always running Iris :-)

2020-11-27 13:03 UTC, velzevur commented
Tests failed with 
```

%%% aecore_sync_SUITE ==> all_nodes.performance.persistence.trusted_peer_is_untrusted_after_a_restart: FAILED
%%% aecore_sync_SUITE ==> {{badmatch,0},
 [{aecore_sync_SUITE,trusted_peer_is_untrusted_after_a_restart,1,
                     [{file,"/home/builder/aeternity/apps/aecore/test/aecore_sync_SUITE.erl"},
                      {line,970}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
```
This is orthogonal to this PR but fixed by #3418

2020-11-30 08:19 UTC, hanssv approved these changes

2020-11-30 08:19 UTC, hanssv commented on apps/aega/src/aega_meta_tx.erl
> -                     ttl         = maps:get(ttl, Args, 0),
Only an issue in tests...

2020-12-01 13:51 UTC, uwiger approved these changes

2020-12-02 13:20 UTC, merged