Make inner tx of PayingForTx non-valid
aeternity/aeternity pull request #3437
Opened 2021-01-01 14:51 UTC by velzevur

Fixes #3054

There is a suggested approach in the issue: use empty `network_id` for signing the inner transaction. This has one big flaw: the inner transaction is repayable on a different network with a different `network_id`. Instead I took a slightly different approach: the inner transaction uses `<netwok_id>-<encoded payer_id>`, so for example it would be used `ae_mainnet-ak_123...`. Note that the payer account's ID is Base58c encoded.

The work on this PR is supported by the Aeternity Crypto Foundation.

2021-01-04 08:35 UTC, hanssv reviewed
I think we should have something static instead of the payer pubkey, it should be possible for "anyone" to pick up the inner tx.

2021-01-04 08:35 UTC, hanssv commented on apps/aecore/test/aec_test_utils.erl
> +sign_tx_with_specific_network_id_prefix(Tx, PrivKey, PubKeyPrefix) ->
Function is named "...network.." and variable "pubkey"... Not obvious.

2021-01-04 08:35 UTC, hanssv commented on apps/aega/test/aega_SUITE.erl
> +    SignedTx = aec_test_utils:sign_tx_with_specific_network_id_prefix(SpendTx,
The long line is easier to read, but if you are on a 640x480 monitor, sure 😛

2021-01-04 16:07 UTC, uwiger approved these changes

2021-01-04 16:37 UTC, gorbak25 requested changes
Please forbid using "-inner_tx" in the network id.
If at some point someone launches "ae_mainnet-inner_tx" then inner transactions from ae_mainnet could be published on "ae_mainnet-inner_tx". When starting/booting the node please hard crash when the network id ends with "-inner_tx" so someone in the future doesn't accidentally shot himself in the foot.

2021-01-04 17:10 UTC, hanssv commented
I wonder if it isn't better to make a quiz with random detailed questions about AE that you have to answer correctly in order to be allowed to start the node? I don't think we will be able to stop truly people from shooting themselves in the foot otherwise?

2021-01-04 17:15 UTC, hanssv approved these changes

2021-01-05 09:53 UTC, gorbak25 approved these changes

2021-01-05 10:33 UTC, merged