Update MacOS to Mojave from High Sierra in CI
aeternity/aeternity pull request #3442
Opened 2021-01-05 12:42 UTC by gorbak25

High Sierra reached EOL status this month and homebrew removed some packages from their repository. This pr bumps the version of the executor to a supported version. 
CI build:
https://app.circleci.com/pipelines/github/aeternity/aeternity/7419/workflows/14b55658-7558-4c9b-8579-6df950fdf646/jobs/133602/steps

2021-01-05 13:10 UTC, velzevur approved these changes

2021-01-05 13:20 UTC, radrow submitted a review, later dismissed

2021-01-05 13:23 UTC, dincho requested changes
Please update the [related docs](https://github.com/aeternity/aeternity/blob/master/docs/installation.md#retrieve-release-binary) and add release notes that this version is no longer supported

2021-01-06 08:32 UTC, velzevur approved these changes

2021-01-06 09:05 UTC, gorbak25 commented
Our High Sierra package builds magically started working again on master. Don't merge this PR for now.

2021-01-06 09:11 UTC, uwiger approved these changes

2021-01-06 10:47 UTC, dincho approved these changes

2021-01-06 10:50 UTC, merged