Call fee
aeternity/aeternity pull request #3593
Opened 2021-04-26 14:25 UTC by radrow

2021-04-26 14:40 UTC, hanssv requested changes

2021-04-26 14:40 UTC, hanssv commented on apps/aefate/src/aefa_fate_op.erl
> +fee(Arg0, EngineState) ->
Available only from Iris!

2021-04-26 15:43 UTC, radrow commented on apps/aefate/src/aefa_fate_op.erl
> +fee(Arg0, EngineState) ->
ah yes

2021-04-26 19:16 UTC, hanssv approved these changes

2021-04-28 09:43 UTC, cytadela8 reviewed
What about the state channel calls to contract?
```
aecontract/src/aect_channel_contract.erl:    {CallRes, Trees, _} = aect_dispatch:run(CTVersion, CallDef),
aecontract/src/aect_channel_contract.erl:    {CallRes, Trees, _} = aect_dispatch:run(#{vm => VmVersion, abi => ABIVersion}, CallDef),
aechannel/src/aesc_utils.erl:            {Call1, _Trees1, _Env1} = aect_dispatch:run(CTVersion, CallDef),
```

They will now fail due to missing `fee` in CallDef

2021-04-28 11:26 UTC, hanssv approved these changes

2021-04-28 11:53 UTC, cytadela8 approved these changes

2021-04-28 12:02 UTC, merged