[2938] cherry pick aec_chain_sim improvements
aeternity/aeternity pull request #3605
Opened 2021-05-03 07:36 UTC by wj2016

2021-05-03 08:16 UTC, cytadela8 requested changes
Missed changes from commit  cd101d91c.

2021-05-03 08:17 UTC, cytadela8 commented
For future refference purposes. Changes in apps/aechannel/test/aesc_chain_watcher_SUITE.erl are from 19cd96dfa9.

2021-05-03 09:01 UTC, wj2016 commented
> For future refference purposes. Changes in apps/aechannel/test/aesc_chain_watcher_SUITE.erl are from [19cd96d](https://github.com/aeternity/aeternity/commit/19cd96dfa9aa919c0329eb539c1f27fd2775b631).

[19cd96d] Upgrade chain simulator (#3358) in case the commit id changes in the future.

2021-05-05 08:38 UTC, cytadela8 commented on apps/aecore/test/aec_chain_sim.erl
> +    Protocol = 5,    %% LIMA protocol, not that it's likely to matter here
Please use the define from aecontract/include/hard_forks.hrl

2021-05-05 08:51 UTC, cytadela8 approved these changes

2021-05-05 10:20 UTC, velzevur approved these changes

2021-05-05 11:43 UTC, uwiger approved these changes

2021-05-05 11:57 UTC, merged