Remove deploy_staking_contract_by_system
aeternity/aeternity pull request #3638
Opened 2021-05-25 11:03 UTC by cna0

Deployment of the staking contract should not be built-in.
`deploy_staking_contract_by_system` was meant for testing purposes, however, I couldn't find any tests relying on it.

2021-05-25 11:53 UTC, cytadela8 commented on apps/aehyperchains/src/aehc_consensus_hyperchains.erl
>  prepare_system_owner(Deployer, Trees) ->
Please remove also prepare_system_owner and cleanup_system_owner. These should be unused now.

2021-05-26 07:08 UTC, cytadela8 reviewed
Logic of state_pre_transform_key_node_consensus_switch could (line 363) be also simplified

2021-05-27 11:03 UTC, cytadela8 approved these changes
Great!

2021-06-02 21:36 UTC, cytadela8 commented
Rebase please

2021-06-03 09:42 UTC, cna0 commented
@cytadela8 Done.

I think we should merge #3647 first, and then I will come back updating this PR.

2021-06-03 13:55 UTC, cytadela8 commented on apps/aecore/src/aec_consensus_common_tests.erl
> +    FakeBlockHash = <<0:?BLOCK_HEADER_HASH_BYTES/unit:8>>,
Looks like you got in rebase commits that shouldn't be there.

2021-06-03 13:56 UTC, cytadela8 requested changes
Fix the rebase

2021-06-03 13:56 UTC, cytadela8 commented
Make sure when rebasing that your local hyperchain-master is up-to-date.

2021-06-03 15:30 UTC, cna0 commented
@cytadela8 Just a side note: rebasing from the target branch is most of the time unnecessary when there's no conflicts.

2021-06-07 18:43 UTC, cytadela8 approved these changes

2022-10-27 13:25 UTC, seanhinde commented
Superseded by new HC design

2022-10-27 13:25 UTC, closed without merging