Hc 3851 core only refactoring
aeternity/aeternity pull request #3643
Opened 2021-05-27 12:57 UTC by rustaem

Draft

2021-05-31 20:40 UTC, cytadela8 reviewed
@rustaem You have commited with merge conflicts :/ Remember to git add after resolving a conflict.

Also please make sure that the tests are passing.

2021-05-31 20:40 UTC, cytadela8 commented on apps/aecore/src/aec_consensus.erl
> +>>>>>>> 2f92aaea... Refactoring, dialyzer coverage
Rebase issue!!!

2021-06-02 21:44 UTC, cytadela8 requested changes

2021-06-02 21:44 UTC, cytadela8 commented on apps/aecore/src/aec_consensus.erl
> +%% Creates a fake key node used for creating new keyblocks - can be blocking
This is a change from hyperchains that should not have been copied.

2021-06-02 21:44 UTC, cytadela8 commented on apps/aecore/src/aec_consensus.erl
> +-spec config_assertion_failed(string(), string(), list()) -> ok | no_return().
This is a change from hyperchains that should not have been copied.

2021-06-02 21:44 UTC, cytadela8 commented on apps/aecore/src/aec_fork_block_settings.erl
> +hc_staking_contract_file() ->
This is a change from hyperchains that should not have been copied.

2021-06-07 17:58 UTC, cytadela8 requested changes
aec_chain_node module is missing. Please make the changes same as for hyperchains so we won't get significant conflicts.

2021-06-08 08:29 UTC, rustaem commented
> aec_chain_node module is missing. Please make the changes same as for hyperchains so we won't get significant conflicts.

aec_chain_node was introduced in ra-3856-hc-and-core-refactoring (PR#3637). Spent some time, but cannot see a realistically simple way to backport those changes here. Want me to backport it hard way or should we postpone until hc merging into master?

2021-11-17 09:13 UTC, closed without merging