Introduce a new HTTP endpoint: /accounts/{pubkey}/next-nonce
aeternity/aeternity pull request #3666
Opened 2021-06-18 14:33 UTC by velzevur

Fixes #3662

The work on this PR is  being suppoeted by ACF.

2021-06-21 17:07 UTC, earlyriser99 commented on apps/aehttp/test/aehttp_integration_SUITE.erl
> +    {Nonce, Nonce} = {Nonce, NextNonce},
Just checking - this is simply an assert right?

2021-06-24 12:54 UTC, uwiger requested changes
Typo in operation id should be fixed

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/priv/oas3.yaml
> +      description: Get an account's next nonce; This is being computed according to whatever is the current account nonce and what transactions are currently present in the transaction pool
```suggestion
      description: Get an account's next nonce; This is computed according to whatever is the current account nonce and what transactions are currently present in the transaction pool
```

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/priv/oas3.yaml
> +          description: "What strategy to use in order to determine the next nonce: shall it check for continuity or return the largest nonce seen + 1. If you choose strategy max - the greatest nonce
```suggestion
          description: "What strategy to use in order to determine the next nonce: shall it check for continuity or return the largest nonce seen + 1. If you choose strategy max, then the greatest nonce seen in the account or currently in the transaction pool is incremented with 1 and returned. If you choose the strategy continuity, then transactions in the mempool are checked if there are gaps - missing nonces that prevent transactions with greater nonces to get included." 
```

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/priv/swagger.yaml
> +      description: "Get an account's next nonce; This is being computed according to whatever is the current account nonce and what transactions are currently present in the transaction pool"
```suggestion
      description: "Get an account's next nonce; This is computed according to whatever is the current account nonce and what transactions are currently present in the transaction pool"
```

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/priv/swagger.yaml
> +          description: "What strategy to use in order to determine the next nonce: shall it check for continuity or return the largest nonce seen + 1. If you choose strategy max - the greatest nonce
```suggestion
          description: "What strategy to use in order to determine the next nonce: shall it check for continuity or return the largest nonce seen + 1. If you choose strategy max, then the greatest nonce seen in the account or currently in the transaction pool is incremented with 1 and returned. If you choose the strategy continuity, then transactions in the mempool are checked if there are gaps - missing nonces that prevent transactions with greater nonces to get included." 
```

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/src/aehttp_dispatch_ext.erl
> +queue('GetAcountNextNonce')                     -> ?READ_Q;
```suggestion
queue('GetAccountNextNonce')                    -> ?READ_Q;
```

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/src/aehttp_dispatch_ext.erl
> +handle_request_('GetAcountNextNonce', Params, _Context) ->
```suggestion
handle_request_('GetAccountNextNonce', Params, _Context) ->
```

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/priv/swagger.yaml
> +      operationId: GetAcountNextNonce
```suggestion
      operationId: GetAccountNextNonce
```

2021-06-24 12:54 UTC, uwiger commented on apps/aehttp/priv/oas3.yaml
> +      operationId: GetAcountNextNonce
```suggestion
      operationId: GetAccountNextNonce
```

2021-07-06 11:32 UTC, uwiger submitted a review, later dismissed

2021-07-07 07:24 UTC, hanssv commented on apps/aecore/src/aec_next_nonce.erl
> +                    Missing =
(Much) shorter: 
`Next = hd(lists:seq(StateTreeNonce, StateTreeNonce + length(AllNoncesInPool) + 1) -- AllNonces)`

2021-07-07 14:17 UTC, uwiger approved these changes

2021-07-07 16:49 UTC, hanssv approved these changes

2021-07-08 11:46 UTC, merged