Revisit staker keys in the config
aeternity/aeternity pull request #4002
Opened 2022-09-01 11:32 UTC by velzevur

Fixes #4000

The work on this PR had been supported by ACF.

2022-09-02 06:22 UTC, fabiankrol submitted a review, later dismissed

2022-09-02 07:38 UTC, loxs approved these changes

2022-09-02 07:45 UTC, loxs requested changes

2022-09-02 07:45 UTC, loxs commented on apps/aecore/src/aec_consensus_smart_contract.erl
> +ensure_keypair(Pubkey, Privkey) ->
Is there a good reason to have two copies of this function?

2022-09-15 13:59 UTC, loxs approved these changes

2022-09-15 14:03 UTC, seanhinde approved these changes

2022-11-08 09:17 UTC, merged