Use foreground mode in docker container, not console -noinput
aeternity/aeternity pull request #4439
Opened 2024-10-15 09:22 UTC by richcarl

This makes the beam process terminate directly on SIGINT as expected of a docker process, instead of bringing up the interactive Break Menu.

2024-10-17 08:31 UTC, dincho requested changes
My comments and reasoning is in some of the old PR's where this has been discussed. It breaks the current workflows (i.e. docker exit with non-zero status code).

2024-10-17 09:04 UTC, richcarl commented
Can you please show me how to reproduce that exit with nonzero status?

2024-10-17 09:28 UTC, richcarl commented
To be clear, if what you say is true then I really want to check what's happening, because that is definitely not what an Erlang system should do with this flag set.

2024-10-18 10:30 UTC, dincho commented
We already discussed it in https://github.com/aeternity/aeternity/pull/4344 and in PM?

This is the current (expected) behaviour:
```
➜  aeternity git:(use-foreground-in-docker) ✗ docker run -it aeternity/aeternity
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Exec: /home/aeternity/node/erts-14.2.1/bin/erlexec -boot /home/aeternity/node/releases/7.2.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /home/aeternity/node/lib -config /home/aeternity/node/releases/7.2.0/sys.config -args_file /home/aeternity/node/releases/7.2.0/vm.args -- console -noinput
Root: /home/aeternity/node
/home/aeternity/node
Adding lager_logger_handler
#{msg=>"adding bootstrap handler"}
10:16:50.547 [info] Setup running ...
10:16:50.549 [info] Directories verified. Res = ok
10:16:50.550 [info] Setup phase [normal] 100
10:16:50.551 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/.aeternity/aeternity
10:16:50.551 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/node
10:16:50.552 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/.epoch/epoch
10:16:50.552 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/node
10:16:50.552 [info] No config file specified; using default settings
10:16:50.552 [info] aeu_env:read_config()-> ok
10:16:50.552 [info] Setup phase [normal] 101
10:16:50.565 [info] OS env config: []
10:16:50.566 [info] Map for OS env config: #{}
10:16:50.566 [info] aeu_env:apply_os_env()-> no_change
10:16:50.566 [info] Setup phase [normal] 102
10:16:50.566 [info] aeu_logging_env:adjust_log_levels()-> ok
10:16:50.566 [info] Setup phase [normal] 103
10:16:50.569 [info] validation: update_config, result: {ok,[#{<<"system">> => #{<<"plugin_path">> => <<"/home/aeternity/node/plugins">>}}]}
10:16:50.569 [info] aeu_plugins:load_plugins()-> ok
10:16:50.569 [info] Setup phase [normal] 110
10:16:50.571 [info] aecore_env:check_env()-> ok
10:16:50.571 [info] aehttp_app:check_env()-> ok
10:16:50.571 [info] aec_consensus:check_env()-> ok
10:16:50.573 [info] aec_hard_forks:ensure_env()-> ok
10:16:50.577 [info] aec_dev_reward:ensure_env()-> ok
10:16:50.577 [info] aec_mining:check_env()-> ok
10:16:50.577 [info] Setup phase [normal] 200
10:16:50.593 [info] Database persist mode true
10:16:50.593 [info] Database backend mnesia_rocksdb
10:16:50.593 [info] Database directory /home/aeternity/node/data/mnesia
10:16:51.051 [info] aec_db:check_db()-> ok
10:16:51.051 [info] Setup phase [normal] 210
10:16:51.058 [info] Enabling direct access for rocksdb
10:16:51.093 [info] Loaded empty persisted chain
10:16:51.094 [info] aec_db:start_db()-> ok
10:16:51.094 [info] Setup phase [normal] 300
10:16:51.094 [info] aedevmode_app:post_check()-> ok
10:16:51.094 [info] Setup phase [normal] 1000
10:16:51.094 [info] Set app_ctrl mode: normal
10:16:51.094 [info] aecore_app:set_app_ctrl_mode()-> ok
10:16:51.094 [info] Setup finished processing hooks (Mode=normal)...
10:16:51.121 [info] Listening for CLI connections at: /var/tmp/mgmtd.aeternity.cli.socket
10:16:51.121 [info] Starting aecore node
10:16:51.127 [info] Initializing keys manager
10:16:51.135 [info] Detailed peer statistics are disabled
10:16:51.201 [info] aec_monitor_metrics_probe:probe_init([ae,epoch,aecore,eper], probe, [{module,aec_monitor_metrics_probe},{type,probe}])
10:16:51.228 [info] Preconfigured channel listeners: []
10:16:51.228 [info] Acceptors default: 1
10:16:51.418 [warning] Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
10:16:51.419 [info] aec_peers started for "pp_9FcMPUr...MqAa2ue"
10:16:51.422 [info] Trusted peers: [#{port => 3015,host => <<"52.220.198.72">>,pubkey => <<221,34,60,123,155,174,109,182,217,78,252,188,87,139,112,240,228,238,238,71,217,164,43,160,203,49,230,243,221,62,173,22>>},#{port => 3015,host => <<"18.217.69.24">>,pubkey => <<36,122,159,139,34,44,227,252,194,116,106,80,92,192,124,227,177,158,250,245,189,244,207,189,230,138,3,218,111,145,251,86>>},#{port => 3015,host => <<"3.17.15.122">>,pubkey => <<217,192,51,96,221,45,138,254,113,140,3,65,143,51,148,110,236,227,91,204,48,254,220,50,53,223,211,124,23,50,172,90>>},#{port => 3015,host => <<"35.166.231.86">>,pubkey => <<132,46,39,17,192,64,188,212,86,156,222,29,197,216,176,182,216,171,16,230,217,134,87,129,16,171,180,107,159,127,184,63>>},#{port => 3015,host => <<"52.11.110.179">>,pubkey => <<55,56,9,82,30,126,3,5,188,49,124,88,153,241,77,245,16,19,9,55,108,94,234,71,227,72,55,42,155,144,162,51>>},#{port => 3015,host => <<"13.250.144.60">>,pubkey => <<114,36,206,142,80,142,228,76,208,101,212,123,9,239,132,249,145,20,3,114,206,143,133,136,223,174,78,240,202,175,88,21>>},#{port => 3015,host => <<"3.17.15.239">>,pubkey => <<186,114,193,224,43,63,193,153,158,160,144,185,176,38,238,12,85,219,25,127,65,168,235,202,169,35,35,236,246,129,47,44>>},#{port => 3015,host => <<"52.26.157.37">>,pubkey => <<17,175,189,200,172,13,117,188,115,80,153,16,109,193,249,144,173,198,104,116,51,32,161,169,141,93,132,31,57,76,89,9>>},#{port => 3015,host => <<"13.228.202.140">>,pubkey => <<53,236,32,181,148,171,213,26,112,126,32,8,50,104,222,1,78,33,117,232,149,184,246,130,57,250,80,102,66,79,93,118>>},#{port => 3015,host => <<"13.53.114.199">>,pubkey => <<14,115,73,12,5,29,78,224,124,47,24,17,18,129,116,42,42,106,106,130,119,233,226,8,185,135,18,43,40,51,135,19>>},#{port => 3015,host => <<"13.53.213.137">>,pubkey => <<176,157,144,114,128,71,93,33,41,211,132,39,206,5,162,207,100,89,77,10,26,240,4,206,167,56,144,160,98,188,186,99>>},#{port => 3015,host => <<"13.53.78.163">>,pubkey => <<48,147,222,160,99,94,115,69,5,94,2,103,90,116,141,100,180,59,230,79,171,57,48,2,224,232,46,46,141,122,129,61>>}]
^C
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
➜  aeternity git:(use-foreground-in-docker) ✗ docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS                      PORTS     NAMES
b6c40c6cf68c   aeternity/aeternity              "bin/aeternity conso…"   31 seconds ago   Exited (0) 27 seconds ago             boring_wu
```

Below the this PR behaviour - not the multiple CTRL+C hits without any handling:

```
➜  aeternity git:(use-foreground-in-docker) ✗ docker run -it aeternity/aeternity:pr-449
Exec: /home/aeternity/node/erts-14.2.1/bin/erlexec -noinput +Bd -boot /home/aeternity/node/releases/7.2.0+34.135e7568c/start -mode embedded -boot_var SYSTEM_LIB_DIR /home/aeternity/node/lib -config /home/aeternity/node/releases/7.2.0+34.135e7568c/sys.config -args_file /home/aeternity/node/releases/7.2.0+34.135e7568c/vm.args -- foreground
Root: /home/aeternity/node
/home/aeternity/node
^CAdding lager_logger_handler
#{msg=>"adding bootstrap handler"}
10:28:02.905 [info] Setup running ...
10:28:02.906 [info] Directories verified. Res = ok
10:28:02.906 [info] Setup phase [normal] 100
10:28:02.906 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/.aeternity/aeternity
10:28:02.906 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/node
10:28:02.906 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/.epoch/epoch
10:28:02.906 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/node
10:28:02.906 [info] No config file specified; using default settings
10:28:02.906 [info] aeu_env:read_config()-> ok
10:28:02.906 [info] Setup phase [normal] 101
10:28:02.909 [info] OS env config: []
10:28:02.909 [info] Map for OS env config: #{}
10:28:02.909 [info] aeu_env:apply_os_env()-> no_change
10:28:02.909 [info] Setup phase [normal] 102
10:28:02.909 [info] aeu_logging_env:adjust_log_levels()-> ok
10:28:02.909 [info] Setup phase [normal] 10 [...]

2024-10-18 10:32 UTC, dincho commented
I don't care about having a Break Menu or whatever it's called, I only care and expect if a hit CTRL+C while running the container in interactive mode (note the `-i`) I want to be able to stop it (clear exit).

2024-10-18 10:33 UTC, dincho commented
Furthermore, It's not clear from the PR description what exact problem this PR is supposed to fix or improve?

2024-10-18 10:43 UTC, dincho commented
I also tested it running in non-interactive mode:

```
➜  aeternity git:(use-foreground-in-docker) ✗ docker run --name ae-pr-449 aeternity/aeternity:pr-449
Exec: /home/aeternity/node/erts-14.2.1/bin/erlexec -noinput +Bd -boot /home/aeternity/node/releases/7.2.0+34.135e7568c/start -mode embedded -boot_var SYSTEM_LIB_DIR /home/aeternity/node/lib -config /home/aeternity/node/releases/7.2.0+34.135e7568c/sys.config -args_file /home/aeternity/node/releases/7.2.0+34.135e7568c/vm.args -- foreground
Root: /home/aeternity/node
/home/aeternity/node
Adding lager_logger_handler
#{msg=>"adding bootstrap handler"}
10:41:14.424 [info] Setup running ...
10:41:14.424 [info] Directories verified. Res = ok
10:41:14.424 [info] Setup phase [normal] 100
10:41:14.424 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/.aeternity/aeternity
10:41:14.424 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/node
10:41:14.426 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/.epoch/epoch
10:41:14.426 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/node
10:41:14.426 [info] No config file specified; using default settings
10:41:14.426 [info] aeu_env:read_config()-> ok
10:41:14.426 [info] Setup phase [normal] 101
10:41:14.429 [info] OS env config: []
10:41:14.429 [info] Map for OS env config: #{}
10:41:14.429 [info] aeu_env:apply_os_env()-> no_change
10:41:14.429 [info] Setup phase [normal] 102
10:41:14.429 [info] aeu_logging_env:adjust_log_levels()-> ok
10:41:14.429 [info] Setup phase [normal] 103
10:41:14.429 [info] validation: update_config, result: {ok,[#{<<"system">> => #{<<"plugin_path">> => <<"/home/aeternity/node/plugins">>}}]}
10:41:14.429 [info] aeu_plugins:load_plugins()-> ok
10:41:14.430 [info] Setup phase [normal] 110
10:41:14.430 [info] aecore_env:check_env()-> ok
10:41:14.430 [info] aehttp_app:check_env()-> ok
10:41:14.430 [info] aec_consensus:check_env()-> ok
10:41:14.430 [info] aec_hard_forks:ensure_env()-> ok
10:41:14.430 [info] aec_dev_reward:ensure_env()-> ok
10:41:14.430 [info] aec_mining:check_env()-> ok
10:41:14.430 [info] Setup phase [normal] 200
10:41:14.434 [info] Database persist mode true
10:41:14.434 [info] Database backend mnesia_rocksdb
10:41:14.434 [info] Database directory /home/aeternity/node/data/mnesia
10:41:14.685 [info] aec_db:check_db()-> ok
10:41:14.685 [info] Setup phase [normal] 210
10:41:14.687 [info] Enabling direct access for rocksdb
10:41:14.703 [info] Loaded empty persisted chain
10:41:14.704 [info] aec_db:start_db()-> ok
10:41:14.704 [info] Set app_ctrl mode: normal
10:41:14.704 [info] Setup phase [normal] 300
10:41:14.704 [info] aedevmode_app:post_check()-> ok
10:41:14.704 [info] Setup phase [normal] 1000
10:41:14.704 [info] aecore_app:set_app_ctrl_mode()-> ok
10:41:14.704 [info] Setup finished processing hooks (Mode=normal)...
10:41:14.712 [info] Listening for CLI connections at: /var/tmp/mgmtd.aeternity.cli.socket
10:41:14.712 [info] Starting aecore node
10:41:14.713 [info] Initializing keys manager
10:41:14.715 [info] Detailed peer statistics are disabled
10:41:14.765 [info] aec_monitor_metrics_probe:probe_init([ae,epoch,aecore,eper], probe, [{module,aec_monitor_metrics_probe},{type,probe}])
10:41:14.769 [info] Preconfigured channel listeners: []
10:41:14.769 [info] Acceptors default: 1
10:41:14.909 [info] aec_peers started for "pp_2V8Nb6m...VTtrscu"
10:41:14.909 [warning] Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
10:41:14.910 [info] Trusted peers: [#{port => 3015,host => <<"52.220.198.72">>,pubkey => <<221,34,60,123,155,174,109,182,217,78,252,188,87,139,112,240,228,238,238,71,217,164,43,160,203,49,230,243,221,62,173,22>>},#{port => 3015,host => <<"18.217.69.24">>,pubkey => <<36,122,159,139,34,44,227,252,194,116,106,80,92,192,124,227,177,158,250,245,189,244,207,189,230,138,3,218,111,145,251,86>>},#{port => 3015,host => <<"3.17.15.122">>,pubkey => <<217,192,51,96,221,45,138,254,113,140,3,65,143,51,148,110,236,227,91,204,48,254,220,50,53,223,211,124,23,50,172,90>>},#{port => 3015,host => <<"35.166.231.86">>,pubkey => <<132,46,39,17,192,64,188,212,86,156,222,29,197,216,176,182,216,171,16,230,217,134,87,129,16,171,180,107,159,127,184,63>>},#{port => 3015,host => <<"52.11.110.179">>,pubkey => <<55,56,9,82,30,126,3,5,188,49,124,88,153,241,77,245,16,19,9,55,108,94,234,71,227,72,55,42,155,144,162,51>>},#{port => 3015,host => <<"13.250.144.60">>,pubkey => <<114,36,206,142,80,142,228,76,208,101,212,123,9,239,132,249,145,20,3,114,206,143,133,136,223,174,78,240,202,175,88,21>>},#{port => 3015,host => <<"3.17.15.239">>,pubkey => <<186,114,193,224,43,63,193,153,158,160,144,185,176,38,238,12,85,219,25,127,65,168,235,202,169,35,35,236,246,129,47,44>>},#{port => 3015,host => <<"52.26.157.37">>,pubkey => <<17,175,189,200,172,13,117,188,115,80,153,16,109,193,249,144,173,198,104,116,51,32,161,169,141,93,132,31,57,76,89,9>>},#{port => 3015,host => <<"13.228.202.140">>,pubkey => <<53,236,32,181,148,171,213,26,112,126,32,8,50,104,222,1,78,33,117,232,149,184,246,130,57,250,80,102,66,79,93,118>>},#{port => 3015,host => <<"13.53.114.199">>,pubkey => <<14,115,73,12,5,29,78,224,124,47,24,17,18,129,116,42,42,106,106,130,119,233,226,8,185,135,18,43,40,51,135,19>>},#{port => 3015,host => <<"13.53.213.137">>,pubkey => <<176,157,144,114,128,71,93,33,41,211,132,39,206,5,162,207,100,89,77,10,26,240,4,206,167,56,144,160,98,188,186,99>>},#{port => 3015,host => <<"13.53.78.163">>,pubkey => <<48,147,222,160,99,94,115,69,5,94,2,103,90,116,141,100,180,59,230,79,171,57,48,2,224,232,46,46,141,122,129,61>>}]
^C10:41:15.184 [info] Starting new sync task #Ref<0.3835002853.2298216449.212417> target is #{hash => <<74,124,248,96,212,34,5,122,104,109,220,123,49,135,184,76,13,71,115,53,9,155,7,9,210,39,24,173,170,142,208,147>>,height => 1019860}
10:41:15.186 [info] Sync stat for #Ref<0.3835002853.2298216449.212417> already in place, updating target to {1019860,<<74,124,248,96,212,34,5,122,104,109,220,123,49,135,184,76,13,71,115,53,9,155,7,9,210,39,24,173,170,142,208,147>>}
^C10:41:15.376 [info] Safe DB-access mode is OFF
10:41:15.376 [info] Synced block  1   (1 generations (1.99 ms/gen), 0 mblock(s), 0 tx(s))
10:41:15.395 [info] Synced block  2   (1 generations (3.50 ms/gen), 1 mblock(s), 1 tx(s))
10:41:15.441 [info] Synced block  3   (1 generations (1.62 ms/gen), 0 mblock(s), 0 tx(s))
10:41:15.452 [info] Sync stat for #Ref<0.3835002853.2298216449.212417> already in place, updating target to {1019860,<<74,124,248,96,212,34,5,122,104,109,220,123,49,135,184,76,13,71,115,53,9,155,7,9,210,39,24,173,170,142,208,147>>}
10:41:15.459 [info] Synced block  4   (1 generations (1.51 ms/gen), 0 mblock(s), 0 tx(s))
10:41:15.467 [info] Sync stat for #Ref<0.3835002853.2298216449.212417> already in place, updating target to {1019860,<<74,124,248,96,212,34,5,122,104,109,220,123,49,135,184,76,13,71,115,53,9,155,7,9,210,39,24,173,170,142,208,147>>}
10:41:15.482 [info] Sync stat for #Ref<0.3835002853.2298216449.212417> already in place, updating target to {1019860,<<74,124,248,96,212,34,5,122,104,109,220,123,49,135,184,76,13,71,115,53,9,155,7,9,210,39,24,173,170,142,208,147>>}
10:41:15.504 [info] Synced block  5   (1 generations (1.79 ms/gen), 0 mblock(s), 0 tx(s))
10:41:15.526 [info] Synced block  6   (1 generations (2.00 ms/gen), 0 mblock(s), 0 tx(s))
^C
got 3 SIGTERM/SIGINTs, forcefully exiting
➜  aeternity git:(use-foreground-in-docker) ✗ docker ps -a --filter name="ae-pr-449"                
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                             PORTS                                         NAMES
170a787e33d6   aeternity/aeternity:pr-449   "bin/aeternity foreg…"   19 seconds ago   Up 19 seconds (health: starting)   3013-3015/tcp, 3113/tcp, 3213/tcp, 3413/tcp   ae-pr-449
```

Note that o [...]

2024-10-18 10:45 UTC, dincho commented
The old image behaviour is to exit (0) immediately without waiting for Break Menu inputs:

```
➜  aeternity git:(use-foreground-in-docker) ✗ docker run aeternity/aeternity
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Exec: /home/aeternity/node/erts-14.2.1/bin/erlexec -boot /home/aeternity/node/releases/7.2.0/start -mode embedded -boot_var SYSTEM_LIB_DIR /home/aeternity/node/lib -config /home/aeternity/node/releases/7.2.0/sys.config -args_file /home/aeternity/node/releases/7.2.0/vm.args -- console -noinput
Root: /home/aeternity/node
/home/aeternity/node
Adding lager_logger_handler
#{msg=>"adding bootstrap handler"}
10:44:01.795 [info] Setup running ...
10:44:01.799 [info] Directories verified. Res = ok
10:44:01.800 [info] Setup phase [normal] 100
10:44:01.801 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/.aeternity/aeternity
10:44:01.801 [info] Searching for config file aeternity.{json,yaml} in directory /home/aeternity/node
10:44:01.802 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/.epoch/epoch
10:44:01.802 [info] Searching for config file epoch.{json,yaml} in directory /home/aeternity/node
10:44:01.802 [info] No config file specified; using default settings
10:44:01.802 [info] aeu_env:read_config()-> ok
10:44:01.802 [info] Setup phase [normal] 101
10:44:01.814 [info] OS env config: []
10:44:01.814 [info] Map for OS env config: #{}
10:44:01.814 [info] aeu_env:apply_os_env()-> no_change
10:44:01.814 [info] Setup phase [normal] 102
10:44:01.815 [info] aeu_logging_env:adjust_log_levels()-> ok
10:44:01.815 [info] Setup phase [normal] 103
10:44:01.817 [info] validation: update_config, result: {ok,[#{<<"system">> => #{<<"plugin_path">> => <<"/home/aeternity/node/plugins">>}}]}
10:44:01.817 [info] aeu_plugins:load_plugins()-> ok
10:44:01.817 [info] Setup phase [normal] 110
10:44:01.818 [info] aecore_env:check_env()-> ok
10:44:01.819 [info] aehttp_app:check_env()-> ok
10:44:01.820 [info] aec_consensus:check_env()-> ok
10:44:01.821 [info] aec_hard_forks:ensure_env()-> ok
10:44:01.824 [info] aec_dev_reward:ensure_env()-> ok
10:44:01.824 [info] aec_mining:check_env()-> ok
10:44:01.824 [info] Setup phase [normal] 200
10:44:01.843 [info] Database persist mode true
10:44:01.843 [info] Database backend mnesia_rocksdb
10:44:01.843 [info] Database directory /home/aeternity/node/data/mnesia
^C
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
➜  aeternity git:(use-foreground-in-docker) ✗ docker ps -a | head -2  
CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS                          PORTS                                         NAMES
af9448f4a0b3   aeternity/aeternity              "bin/aeternity conso…"   About a minute ago   Exited (0) About a minute ago                                                 quirky_herschel
```

2024-10-18 10:48 UTC, richcarl commented
Thank you for the details. I will investigate.

2024-10-18 12:00 UTC, richcarl commented
> It's not clear from the PR description what exact problem this PR is supposed to fix or improve?

I could have been clearer. I wanted to change it because the current code is doing something quite nonstandard, instead of using the standard mode that is designed for cases like running in Docker, and there was no explanation why it was doing this. If there is a reasonable motivation for it, we should keep it but document why.

2024-10-18 12:18 UTC, richcarl commented
> I don't care about having a Break Menu or whatever it's called, I only care and expect if a hit CTRL+C while running the container in interactive mode (note the `-i`) I want to be able to stop it (clear exit).

I see now. The thing is that it's not generally expected of a service in Docker to react to CTRL+C (SIGINT). The process runs as PID 1 (the "init" process), which is special, and the kernel will ignore a SIGINT to PID 1 unless the code has installed its own nonstandard handler. To stop the process you're supposed to use 'docker stop' from the outside, which forwards a SIGTERM (or SIGKILL after a few seconds if there is no reaction). For example, when Kubernetes stops a pod, it is via SIGTERM/SIGKILL.

A big reason for ignoring SIGINT is that if someone does 'docker attach' to a running system, they should not accidentally kill the service if they hit CTRL+C.

What Erlang does in the normal case is to install a special SIGINT handler that brings up the Break menu on CTRL+C. When started with 'foreground' instead of 'console', it skips this handler. That's why it stops reacting to CTRL+C, and it is intentional in foreground mode, for safety in production.

If you still want to be able to use CTRL+C anyway, we can just document why it's done that way.

2024-10-18 12:48 UTC, richcarl commented
> When started with 'foreground' instead of 'console', it skips this handler. That's why it stops reacting to CTRL+C.

This wasn't quite true, but the effect is the same: 'foreground' mode skips installing the handler but it does not ignore the signal either, it just stops using the Break menu. It's because the process is PID 1 that SIGINT is filtered out when there is no special handler. It's possible to use a wrapper program like 'tini' to make the Erlang process not be PID 1, but that's probably overkill.

2024-10-18 13:07 UTC, closed without merging

2024-10-18 13:08 UTC, richcarl commented
#4442 Documents current behaviour.

2024-10-21 15:41 UTC, dincho commented
> It's possible to use a wrapper program like 'tini' to make the Erlang process not be PID 1, but that's probably overkill.

I don't really see a reason for that as `console -noinput` works exactly as expected (this is how most of the containers I've ever used react to CTRL+C)

2024-10-21 15:42 UTC, dincho commented
> > It's not clear from the PR description what exact problem this PR is supposed to fix or improve?
> 
> I could have been clearer. I wanted to change it because the current code is doing something quite nonstandard, instead of using the standard mode that is designed for cases like running in Docker, and there was no explanation why it was doing this. If there is a reasonable motivation for it, we should keep it but document why.

I admit I rarely document some weird cases, I'll try to do better