Pinning Agent reactor to `new_epoch`event
aeternity/aeternity pull request #4499
Opened 2024-11-21 13:14 UTC by klercker

Move pinning agent invocation code from inner consensus callbacks to separate gen_server+worker process.

2024-11-22 08:45 UTC, klercker commented on apps/aecore/src/aec_pinning_agent.erl
> +    % case aec_parent_connector:has_parent_account(LastLeader) of
Oops, was that still in there?! I'll hold on with comitting in case some other comments drop in.

2024-11-22 12:10 UTC, hanssv requested changes
The gen-server process should be enough to run this, it is even aptly named something_worker. Spawning yet another process is overkill.

2024-11-22 12:10 UTC, hanssv commented on apps/aecore/src/aec_pinning_agent.erl
> +            register(?WORKER, Pid),
This is not the unique name `my_unique_process` that is tested for above?  

But bigger question, why on earth do we spawn yet another process in here, and also wait for another top change.

2024-11-22 14:26 UTC, klercker commented
The `gen_server` process is actually named `?SERVER` as per usual, the sub process is `?MODULE_worker`. Again, the state handling becomes a lot cleaner with the spawned process, and that single process is pretty cheap as we all know.

2024-11-22 16:06 UTC, hanssv commented on apps/aecore/src/aec_pinning_agent.erl
> +    gen_server:stop(?SERVER).
This is an API function, not a callback

2024-11-22 16:06 UTC, hanssv commented on apps/aecore/src/aec_pinning_agent.erl
> +    lager:debug("STOPPED"),
Is that logging really necessary 🤔

2024-11-22 16:08 UTC, hanssv commented
> The `gen_server` process is actually named `?SERVER` as per usual, the sub process is `?MODULE_worker`. Again, the state handling becomes a lot cleaner with the spawned process, and that single process is pretty cheap as we all know.

Yes, naming looks updated and correct, the drawback of spawning yet another process is that you need to register for events every time, etc. It is much cleaner and not a lot of work to just put that logic directly in the gen_server.

2024-11-22 16:37 UTC, klercker commented
As per "advice" from @richcarl and @happi and others I put it in a separate worker process and I like the look of it (and I really don't like the look of `gen_server`; it's a great pattern/whatever but the code looks like the llamas arse). I think the number of LOC managing event subscription will actually be higher with `gen_server` but my .erl incompetence might be fooling me here. Since you might or might not want to listen to `top_change` all the time (when you are not pinning), you need to either match for it somewhere (unpacking `#state{}` etc) or turn on and off subscription as you go along. But please prove me wrong.

If it's very very important to you @hanssv, I will refac again, but I really do like the current impl and it's not particularly non-standard.

2024-11-22 17:45 UTC, klercker commented
Not superior perhaps, but valid 😅

2024-11-25 10:54 UTC, hanssv approved these changes
Looks good, this one is much nicer!

2024-11-25 10:54 UTC, hanssv commented on apps/aehttp/src/aehttpc_aeternity.erl
> +        , nonce       => Nonce
Indentation?

2024-11-25 11:16 UTC, mitchelli approved these changes

2024-11-25 11:45 UTC, happi approved these changes

2024-11-25 11:47 UTC, merged